print('rewre')
print('fds')
print('hello python')
print('fwd')
print('gfgh')
print('hello python')
print('rewwwer')
print('reteert')
print('reteertghl')
print('ars dayn')
print('gfgh')
print('hello python')
print('rewwwer')
print('reteert')
print('reteertghl')

